// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// Data reducer types
export const SET_SEMUA_PENGADUAN = 'SET_SEMUA_PENGADUAN';
export const SET_PENGADUAN = 'SET_PENGADUAN';
export const LIKE_PENGADUAN = 'LIKE_PENGADUAN';
export const UNLIKE_PENGADUAN = 'UNLIKE_PENGADUAN';
export const DELETE_PENGADUAN = 'DELETE_PENGADUAN';
export const POST_PENGADUAN = 'POST_PENGADUAN';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
